[package]
name = "glacier_ctf"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.10", default-features = true, features = [
  "abigen",
  "rustls",
] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
eyre = "0.6"
